# Generated by Django 5.0.6 on 2024-05-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshortenerapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                ("short_url", models.URLField(blank=True)),
                ("hash_value", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Url",
        ),
    ]
