# Generated by Django 5.0.6 on 2024-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshortenerapp", "0002_shortlink_delete_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shortlink",
            name="short_url",
        ),
        migrations.AddField(
            model_name="shortlink",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shortlink",
            name="hash_value",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
